name = "doctorai-connect"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "doctorai"
database_id = "doctorai-db"

[ai]
binding = "AI"

[vars]
CORS_ORIGINS = "http://127.0.0.1:5173,http://localhost:5173"

[dev]
port = 8787
